version: '3.8'

services:
  backend:
    build:
      context: ./backend_Project
      dockerfile:  docker/python/Dockerfile
    volumes:
      - ./backend_Project/backend:/backend
    ports:
      - 8000:8000
    command: python3 /backend/manage.py runserver 0.0.0.0:8000
    tty: true
    depends_on:
      - db

  db:
    image: postgres
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgres"

  frontend:
    build:
      context: ./frontend_Project
      dockerfile: docker/node/Dockerfile
    volumes:
      - ./frontend_Project/node/frontend:/usr/src/app/frontend
    command: sh -c "cd /usr/src/app/frontend && yarn start"
    ports:
      - "3000:3000"
